defaults:
  - _self_
  - task: mimicgen_abs

name: act
_target_: equi_diffpo.workspace.train_act_workspace.TrainActWorkspace

shape_meta: ${task.shape_meta}
exp_name: "default"

task_name: stack_d1
n_demo: 200
horizon: 10
n_obs_steps: 1
n_action_steps: 10
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
past_action_visible: False
dataset: equi_diffpo.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
dataset_path: data/robomimic/datasets/${task_name}/${task_name}_abs.hdf5

policy:
  _target_: equi_diffpo.policy.act_policy.ACTPolicyWrapper

  shape_meta: ${shape_meta}
  
  max_timesteps: ${task.env_runner.max_steps}
  temporal_agg: false
  n_envs: ${task.env_runner.n_envs}
  horizon: ${horizon}

dataloader:
  batch_size: 64
  num_workers: 4
  shuffle: True
  pin_memory: True
  persistent_workers: True

val_dataloader:
  batch_size: 64
  num_workers: 4
  shuffle: False
  pin_memory: True
  persistent_workers: True

training:
  device: "cuda:0"
  seed: 0
  debug: False
  resume: True
  num_epochs: ${eval:'50000 / ${n_demo}'}
  rollout_every: ${eval:'1000 / ${n_demo}'}
  checkpoint_every: ${eval:'1000 / ${n_demo}'}
  val_every: 1
  max_train_steps: null
  max_val_steps: null
  tqdm_interval_sec: 1.0

logging:
  project: diffusion_policy_${task_name}
  resume: True
  mode: online
  name: act_demo${n_demo}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 5
    format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}
